### ISSUE TITLE
Code should be marked up as code sections

### ISSUE THREAD

**Issue by JanX2** [jnozzi/cocoadev.com#5]
See http://daringfireball.net/projects/markdown/syntax#precode

**Comment by jnozzi** [comment]
Exporting the page data while preserving markup (or simply mass-applying changes to the most common cases) has been a challenging issue several developers have offered to attempt. None have followed through, though. You're more than welcome to try it on your own clone and issue a pull request when you feel it's ready.

**Comment by jnozzi** [comment]
After years of nobody volunteering to do this or offering any other kind of substantive help, it's clear the community has moved on and is content to let the site remain an archive. I'm going to go ahead and close this.
