### ISSUE TITLE
Access to the original CocoaDev.com files and database?

### ISSUE THREAD

**Issue by tonyarnold** [jnozzi/cocoadev.com#7]
Hi @jnozzi — while I appreciate the efforts you've put into rebuilding CocoaDev, there's a lot of conversion problems in the Markdown and I'd really like to reference some of the materials in a non-broken manner. 

Would it be possible to get a copy of the original CocoaDev.com as it was before you took over? Thanks!

**Comment by jnozzi** [comment]
Nothing is stopping anyone from forking and running their own cleanup scripts. However, after years of nobody volunteering to do this or offering any other kind of substantive help, it's clear the community has moved on and is content to let the site remain an archive. I'm going to go ahead and close this.
