### ISSUE TITLE
FOSS license for code-snippets from cocoadev.com (NSData+Category)?

### ISSUE THREAD

**Issue by woa1mu** [jnozzi/cocoadev.com#9]
Hello Joshua,

I have tracked a code-snippet from https://github.com/schacon/igithub/blob/master/CocoaGit/Util/NSData%2BCompression.m to your repo here. I saw a comment with the hint to "http://www.cocoadev.com/index.pl?NSDataCategory".

It seems that the code for zlibInflate/zlibDeflate is originally from you and was published on cocoadev.com - is this correct? 
We are also using this code and I am trying to comply with FOSS guidelines. 
Have you published this code under a specific license?

Kind regards,
Andy

**Comment by jnozzi** [comment]
Andy:

While I’d made in the 2000s a number of contributions to the now-defunct CocoaDev wiki, the code you referenced is not one of them. All code and information posted to that wiki fell (and still falls) under the Creative Commons license and as such is public domain.

**Comment by jnozzi** [comment]
Adding: I took over managing the now-static content (as an archivist) and paying for the domain to point to it years back from Scott Stevenson, who no longer had the time or inclination to keep up with wiki spam and maintenance.

**Comment by woa1mu** [comment]
Thanks Joshua for your response! This is very helpful information.
